import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { env } from "@/lib/env";

export const C = {
  ink: "#201e1d",
  muted: "#6b6866",
  line: "#d8d5cd",
  accent: "#006786",
  bg: "#ffffff",
};

export const s = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: C.ink, fontFamily: "Helvetica", lineHeight: 1.5 },
  h1: { fontSize: 18, fontFamily: "Times-Bold", marginBottom: 2 },
  h2: { fontSize: 13, fontFamily: "Times-Bold", marginBottom: 6, marginTop: 12 },
  small: { fontSize: 8, color: C.muted },
  hr: { borderBottomWidth: 1, borderBottomColor: C.line, marginVertical: 10 },
  row: { flexDirection: "row", justifyContent: "space-between" },
  label: { color: C.muted },
  th: { fontSize: 8, color: C.muted, textTransform: "uppercase", letterSpacing: 0.5 },
  cell: { paddingVertical: 4, paddingRight: 8 },
  trBorder: { borderBottomWidth: 1, borderBottomColor: C.line },
  badge: { fontSize: 8, color: C.accent },
});

export function Letterhead({ subtitle }: { subtitle?: string }) {
  return (
    <View>
      <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" }}>
        <View>
          <Text style={s.h1}>{env.school.name}</Text>
          <Text style={s.small}>{env.school.address}</Text>
          <Text style={s.small}>
            {env.school.phone} · {env.school.email}
            {env.school.eiin ? ` · EIIN ${env.school.eiin}` : ""}
          </Text>
        </View>
        {subtitle && <Text style={{ fontSize: 11, fontFamily: "Times-Bold" }}>{subtitle}</Text>}
      </View>
      <View style={s.hr} />
    </View>
  );
}

export function Footer({ note }: { note?: string }) {
  return (
    <View style={{ position: "absolute", bottom: 24, left: 40, right: 40 }}>
      <View style={{ borderTopWidth: 1, borderTopColor: C.line, paddingTop: 6, flexDirection: "row", justifyContent: "space-between" }}>
        <Text style={s.small}>{note ?? `Generated by Seltiv SLMS · ${env.school.name}`}</Text>
        <Text style={s.small} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
      </View>
    </View>
  );
}

export function KeyVal({ k, v }: { k: string; v: string }) {
  return (
    <View style={{ flexDirection: "row", marginBottom: 3 }}>
      <Text style={{ width: 110, color: C.muted }}>{k}</Text>
      <Text>{v}</Text>
    </View>
  );
}

export function Sheet({
  title,
  children,
  footerNote,
}: {
  title: string;
  children: React.ReactNode;
  footerNote?: string;
}) {
  return (
    <Document title={title}>
      <Page size="A4" style={s.page}>
        <Letterhead subtitle={title} />
        {children}
        <Footer note={footerNote} />
      </Page>
    </Document>
  );
}
